paths:
  save: /mnt/stocks

following:
  GFT: Bill Gates
  AQ: Guy Spier
  BRK: Warren Buffet

keys:
  alpha-vantage: abc123
  finnhub: def456

metrics:
  - rolling/3-year
  - rolling/5-year
  - rolling/10-year
