locale: US/Eastern
paths:
  save: /mnt/stocks

portfolios:
  - name: Experts
    type: follow
    shared: True
    symbols:
      - GFT
      - BRK
  - name: ETFs
    type: manual
    symbols:
      - VTI
      - SPY

keys:
  alpha_vantage: null
  finnhub: null
  metals: null

metrics:
  - rolling/3-year
  - rolling/5-year
  - rolling/10-year
